import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "Welcome to HadiKid": "Welcome to HadiKid",
      "Let's get you started!": "Let's get you started!",
      "Get started by inviting friends to join your carpool.":
          "Get started by inviting friends to join your carpool.",
      "Create Carpool": "Create Carpool",
      "How to Works": "How to Works",
      "Create a carpool between two points.":
          "Create a carpool between two points.",
      "Invite your friends to carpool with you.":
          "Invite your friends to carpool with you.",
      "Friends join and add their child's location.":
          "Friends join and add their child's location.",
      "Parents Volunteer to Drive. We Send reminders and optimized routes.":
          "Parents Volunteer to Drive. We Send reminders and optimized routes.",
      "Next": "Next",
      "Step": "Step",
      "Let’s set up an account": "Let’s set up an account",
      "I agree to HadiKid's ": "I agree to HadiKid's ",
      "Terms & Conditions": "Terms & Conditions",
      " and ": " and ",
      "Privacy Policy": "Privacy Policy",
      "Sign Up": "Sign Up",
      "Already have an account?": "Already have an account?",
      "Sign In": "Sign In",
      "Sign In Your Account": "Sign In Your Account",
      "Remember me": "Remember me",
      "Forgot password?": "Forgot password?",
      "Resset password": "Resset password",
      "Verification": "Verification",
      "An OTP code has been sent to": "An OTP code has been sent to",
      " to reset password. If you don't see it in your inbox, please check your junk or spam folder. Enter the code below to continue.":
          " to reset password. If you don't see it in your inbox, please check your junk or spam folder. Enter the code below to continue.",
      " to reset your password. Enter the code below to continue.":
          " to reset your password. Enter the code below to continue.",
      "Times remaining": "Times remaining",
      "resend": "resend",
      "Enter your mobile number": "Enter your mobile number",
      "Enter your email": "Enter your email",
      "Verify with Email": "Verify with Email",
      "Verify with Phone": "Verify with Phone",
      "Create new password": "Create new password",
      "Create new password here": "Create new password here",
      "Done": "Done",
      "Add a child": "Add a child",
      "Add child": "Add child",

      // Create carpool
      "Create carpool": "Create carpool",
      "Which child(ren) will attend the event?*":
          "Which child(ren) will attend the event?*",
      "Add new child(ren)": "Add new child(ren)",
      "My Role": "My Role",
      "What": "What",
      "Where": "Where",
      "Would you like to set this location as your home address?":
          "Would you like to set this location as your home address?",
      "Okay": "Okay",
      "Later": "Later",
      "When": "When",
      "Does not repeat": "Does not repeat",
      "Daily": "Daily",
      "Every week": "Every week",
      "Custom": "Custom",
      "Select Days": "Select Days",
      "Repeat Until": "Repeat Until",
      "Select a date": "Select a date",
      'Create return trip': 'Create return trip',
      "Enter Return date": "Enter Return date",
      "Preview & Invites": "Preview & Invites",
      "Invite": "Invite",
      "Searching the parent": "Searching the parent",
      "Add Contacts": "Add Contacts",
      "Add Message": "Add Message",
      "Carpool Details": "Carpool Details",
      "Event Name": "Event Name",
      "From": "From",
      "To": "To",
      "On": "On",
      "Edit": "Edit",
      "Send": "Send",
      "Invites": "Invites",
      "Home": "Home",
      "Invitation is Successfull!": "Invitation is Successfull!",
      "Invite Sent!": "Invite Sent!",

      // Find family
      "Find Families": "Find Families",

      // inbox
      "Inbox": "Inbox",
      "Chats": "Chats",
      "Contact Invites": "Contact Invites",
      "Carpool Invites": "Carpool Invites",
      'No carpool invitations yet': 'No carpool invitations yet',
      'No chats yet': 'No chats yet',
      'No invitations yet': 'No invitations yet',

      // Menu
      "Upgrade to HadiKid Premium!": "Upgrade to HadiKid Premium!",
      "Enjoy exclusive features with 7 days FREE — no strings attached! Ready to upgrade?":
          "Enjoy exclusive features with 7 days FREE — no strings attached! Ready to upgrade?",
      "Not Now": "Not Now",
      "Learn More": "Learn More",
      "Account Settings": "Account Settings",
      'Notification of Changes': 'Notification of Changes',
      'Changes to carpools I set up': 'Changes to carpools I set up',
      'Changes affecting my family': 'Changes affecting my family',
      'Changes affecting my driving': 'Changes affecting my driving',
      'Driving Reminders': 'Driving Reminders',
      "minutes before": "minutes before",
      "hour before": "hour before",
      "hours before": "hours before",
      'Participation Reminders': 'Participation Reminders',
      'Carpool Notes Notifications': 'Carpool Notes Notifications',
      'Notify me of new messages': 'Notify me of new messages',
      'Child Pickup / Drop-off': 'Child Pickup / Drop-off',
      'Preference': 'Preference',
      'Receive notifications and invitations via:':
          'Receive notifications and invitations via:',
      'Email': 'Email',
      'Push': 'Push',
      "Manage Subscription": "Manage Subscription",
      "Edit child": "Edit child",
      "Save": "Save",
      "Language": "Language",
      "Menu": "Menu",
      'Carpools': 'Carpools',
      'Profile': 'Profile',
      'Contact List': 'Contact List',
      'Account Setting': 'Account Setting',
      'Payment': 'Payment',
      'Support': 'Support',
      'Share HadiKid with Friends': 'Share HadiKid with Friends',
      'Logout': 'Logout',
      "Are you sure you want to logout?": "Are you sure you want to logout?",
      'Delete My Account': 'Delete My Account',
      "Delete Account": "Delete Account",
      "Are you sure you want to delete your account?":
          "Are you sure you want to delete your account?",
      "Delete": "Delete",
      'Cancel': 'Cancel',
      "Upcoming": "Upcoming",
      "History": "History",
      "As a Driver": "As a Driver",
      'No data yet': 'No data yet',
      "My Family Members": "My Family Members",
      "Children": "Children",
      "Spouse": "Spouse",
      "No children added yet.": "No children added yet.",
      "My contact list": "My contact list",
      "My Information": "My Information",
      "Daniel Austin": "Daniel Austin",
      "Home Address": "Home Address",
      "Your home address will allow you to send or receive ‘Add Contact’ requests to connect with HadiKid families nearby.":
          "Your home address will allow you to send or receive ‘Add Contact’ requests to connect with HadiKid families nearby.",
      "My Profile": "My Profile",
      "Packages": "Packages",
      "Hadikid Free": "Hadikid Free",
      "Hadikid Premium": "Hadikid Premium",
      'HadiKid No Ads': 'HadiKid No Ads',
      'Live Tracking': 'Live Tracking',
      'Added Notification': 'Added Notification',
      'Carpool History': 'Carpool History',
      'Add message': 'Add message',
      'Choose between monthly or yearly billing and start enjoying your premium features.':
          'Choose between monthly or yearly billing and start enjoying your premium features.',
      "Update": "Update",
      "Schedule": "Schedule",
      "Attending": "Attending",
      "Driving": "Driving",
    },
    'tr_TR': {
      "Welcome to HadiKid": "HadiKid'e Hoş Geldiniz",
      "Let's get you started!": "Hadi başlayalım!",
      "Get started by inviting friends to join your carpool.": "Araba paylaşımına arkadaşlarını davet ederek başla.",
      "Create Carpool": "Araba Paylaşımı Oluştur",
      "How to Works": "Nasıl Çalışır",
      "Create a carpool between two points.": "İki nokta arasında araba paylaşımı oluşturun.",
      "Invite your friends to carpool with you.": "Arkadaşlarınızı araba paylaşımına davet edin.",
      "Friends join and add their child's location.": "Arkadaşlar katılır ve çocuklarının konumunu ekler.",
      "Parents Volunteer to Drive. We Send reminders and optimized routes.": "Ebeveynler Sürücü Olarak Gönüllü Olur. Hatırlatıcılar ve optimize edilmiş rotalar göndeririz.",
      "Next": "Sonraki",
      "Step": "Adım",
      "Let’s set up an account": "Hadi bir hesap oluşturalım",
      "I agree to HadiKid's ": "HadiKid'in ",
      "Terms & Conditions": "Kullanım Koşulları",
      " and ": " ve ",
      "Privacy Policy": "Gizlilik Politikası",
      "Sign Up": "Kayıt Ol",
      "Already have an account?": "Zaten bir hesabınız var mı?",
      "Sign In": "Giriş Yap",
      "Sign In Your Account": "Hesabınıza Giriş Yapın",
      "Remember me": "Beni hatırla",
      "Forgot password?": "Şifrenizi mi unuttunuz?",
      "Resset password": "Şifreyi Sıfırla",
      "Verification": "Doğrulama",
      "An OTP code has been sent to": "Bir OTP kodu gönderildi",
      " to reset password. If you don't see it in your inbox, please check your junk or spam folder. Enter the code below to continue.": " şifrenizi sıfırlamak için. Gelen kutunuzda göremiyorsanız, lütfen gereksiz veya spam klasörünüzü kontrol edin. Devam etmek için aşağıdaki kodu girin.",
      " to reset your password. Enter the code below to continue.": " şifrenizi sıfırlamak için. Devam etmek için aşağıdaki kodu girin.",
      "Times remaining": "Kalan süre",
      "resend": "tekrar gönder",
      "Enter your mobile number": "Telefon numaranızı girin",
      "Enter your email": "E-postanızı girin",
      "Verify with Email": "E-posta ile Doğrula",
      "Verify with Phone": "Telefon ile Doğrula",
      "Create new password": "Yeni şifre oluştur",
      "Create new password here": "Burada yeni şifre oluşturun",
      "Done": "Tamamlandı",
      "Add a child": "Çocuk ekle",
      "Add child": "Çocuk ekle",

      // Create carpool
      "Create carpool": "Araba paylaşımı oluştur",
      "Which child(ren) will attend the event?*": "Hangi çocuk(lar) etkinliğe katılacak?*",
      "Add new child(ren)": "Yeni çocuk(lar) ekle",
      "My Role": "Rolüm",
      "What": "Ne",
      "Where": "Nerede",
      "Would you like to set this location as your home address?": "Bu konumu ev adresiniz olarak ayarlamak ister misiniz?",
      "Okay": "Tamam",
      "Later": "Sonra",
      "When": "Ne zaman",
      "Does not repeat": "Tekrarlanmaz",
      "Daily": "Günlük",
      "Every week": "Haftalık",
      "Custom": "Özel",
      "Select Days": "Günleri Seç",
      "Repeat Until": "Tekrar Son Tarihi",
      "Select a date": "Bir tarih seçin",
      'Create return trip': 'Dönüş yolculuğu oluştur',
      "Enter Return date": "Dönüş tarihini girin",
      "Preview & Invites": "Önizleme ve Davetler",
      "Invite": "Davet Et",
      "Searching the parent": "Ebeveyn aranıyor",
      "Add Contacts": "Kişi Ekle",
      "Add Message": "Mesaj Ekle",
      "Carpool Details": "Araba Paylaşımı Detayları",
      "Event Name": "Etkinlik Adı",
      "From": "Başlangıç",
      "To": "Varış",
      "On": "Tarih",
      "Edit": "Düzenle",
      "Send": "Gönder",
      "Invites": "Davetler",
      "Home": "Ana Sayfa",
      "Invitation is Successfull!": "Davet Başarılı!",
      "Invite Sent!": "Davet Gönderildi!",

      // Find family
      "Find Families": "Aile Bul",

      // inbox
      "Inbox": "Gelen Kutusu",
      "Chats": "Sohbetler",
      "Contact Invites": "Kişi Davetleri",
      "Carpool Invites": "Araba Paylaşım Davetleri",
      'No carpool invitations yet': 'Henüz araba paylaşım davetiniz yok',
      'No chats yet': 'Henüz sohbet yok',
      'No invitations yet': 'Henüz davet yok',

      // Menu
      "Upgrade to HadiKid Premium!": "HadiKid Premium'a Yükselt!",
      "Enjoy exclusive features with 7 days FREE — no strings attached! Ready to upgrade?": "7 gün ÜCRETSİZ özel özelliklerden yararlanın — hiçbir taahhüt yok! Yükseltmeye hazır mısınız?",
      "Not Now": "Şimdi Değil",
      "Learn More": "Daha Fazla Bilgi",
      "Account Settings": "Hesap Ayarları",
      'Notification of Changes': 'Değişiklik Bildirimleri',
      'Changes to carpools I set up': 'Oluşturduğum araba paylaşımlarındaki değişiklikler',
      'Changes affecting my family': 'Ailemi etkileyen değişiklikler',
      'Changes affecting my driving': 'Sürüşümü etkileyen değişiklikler',
      'Driving Reminders': 'Sürüş Hatırlatıcıları',
      "minutes before": "dakika önce",
      "hour before": "saat önce",
      "hours before": "saat önce",
      'Participation Reminders': 'Katılım Hatırlatıcıları',
      'Carpool Notes Notifications': 'Araba Paylaşım Notu Bildirimleri',
      'Notify me of new messages': 'Yeni mesajlar için beni bilgilendir',
      'Child Pickup / Drop-off': 'Çocuk Alma / Bırakma',
      'Preference': 'Tercih',
      'Receive notifications and invitations via:': 'Bildirimleri ve davetleri şu yolla al:',
      'Email': 'E-posta',
      'Push': 'Push',
      "Manage Subscription": "Aboneliği Yönet",
      "Edit child": "Çocuğu düzenle",
      "Save": "Kaydet",
      "Language": "Dil",
      "Menu": "Menü",
      'Carpools': 'Araba Paylaşımları',
      'Profile': 'Profil',
      'Contact List': 'Kişi Listesi',
      'Account Setting': 'Hesap Ayarları',
      'Payment': 'Ödeme',
      'Support': 'Destek',
      'Share HadiKid with Friends': "HadiKid'i Arkadaşlarla Paylaş",
      'Logout': 'Çıkış Yap',
      "Are you sure you want to logout?": "Çıkış yapmak istediğinizden emin misiniz?",
      'Delete My Account': 'Hesabımı Sil',
      "Delete Account": "Hesabı Sil",
      "Are you sure you want to delete your account?": "Hesabınızı silmek istediğinizden emin misiniz?",
      "Delete": "Sil",
      'Cancel': 'İptal',
      "Upcoming": "Yaklaşan",
      "History": "Geçmiş",
      "As a Driver": "Sürücü Olarak",
      'No data yet': 'Henüz veri yok',
      "My Family Members": "Aile Üyelerim",
      "Children": "Çocuklar",
      "Spouse": "Eş",
      "No children added yet.": "Henüz çocuk eklenmedi.",
      "My contact list": "Kişi listem",
      "My Information": "Bilgilerim",
      "Daniel Austin": "Daniel Austin",
      "Home Address": "Ev Adresi",
      "Your home address will allow you to send or receive 'Add Contact' requests to connect with HadiKid families nearby.": "Ev adresiniz, yakındaki HadiKid aileleriyle bağlantı kurmak için 'Kişi Ekle' istekleri göndermenize veya almanıza olanak tanır.",
      "My Profile": "Profilim",
      "Packages": "Paketler",
      "Hadikid Free": "Hadikid Ücretsiz",
      "Hadikid Premium": "Hadikid Premium",
      'HadiKid No Ads': 'HadiKid Reklamsız',
      'Live Tracking': 'Canlı Takip',
      'Added Notification': 'Eklenen Bildirimler',
      'Carpool History': 'Araba Paylaşım Geçmişi',
      'Add message': 'Mesaj ekle',
      'Choose between monthly or yearly billing and start enjoying your premium features.': 'Aylık veya yıllık faturalandırma arasında seçim yapın ve premium özelliklerinizin tadını çıkarmaya başlayın.',
      "Update": "Güncelle",
      "Schedule": "Program",
      "Attending": "Katılıyor",
      "Driving": "Sürüş",
    },
  };
}
